"""add incident relationship to threat scores

Revision ID: c34a0d5b77ea
Revises: fea3ba3a397d
Create Date: 2026-08-09 19:43:56.023601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c34a0d5b77ea'
down_revision: Union[str, Sequence[str], None] = 'fea3ba3a397d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threat_scores', sa.Column('incident_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_threat_scores_incident_id'), 'threat_scores', ['incident_id'], unique=False)
    op.create_foreign_key(None, 'threat_scores', 'incidents', ['incident_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'threat_scores', type_='foreignkey')
    op.drop_index(op.f('ix_threat_scores_incident_id'), table_name='threat_scores')
    op.drop_column('threat_scores', 'incident_id')
    # ### end Alembic commands ###
