"""create threat_scores table

Revision ID: c6026964b2d8
Revises: fb4bd5d82dfd
Create Date: 2026-08-07 21:34:56.093477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6026964b2d8'
down_revision: Union[str, Sequence[str], None] = 'fb4bd5d82dfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('threatlens_score', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('recommendation', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_scores_id'), 'threat_scores', ['id'], unique=False)
    op.create_index(op.f('ix_threat_scores_ip_address'), 'threat_scores', ['ip_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_scores_ip_address'), table_name='threat_scores')
    op.drop_index(op.f('ix_threat_scores_id'), table_name='threat_scores')
    op.drop_table('threat_scores')
    # ### end Alembic commands ###
