"""Rename incident source_ip to ip_address

Revision ID: cf14bc68d99d
Revises: e38b5abe23ab
Create Date: 2026-08-09 16:51:53.238768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf14bc68d99d'
down_revision: Union[str, Sequence[str], None] = 'e38b5abe23ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_ip_address'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_column('incidents', 'assigned_to')
    op.drop_column('incidents', 'resolution_notes')
    op.drop_column('incidents', 'threatlens_score')
    op.drop_column('incidents', 'priority')
    op.drop_column('incidents', 'recommendation')
    op.drop_column('incidents', 'resolved_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('incidents', sa.Column('recommendation', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('incidents', sa.Column('priority', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('incidents', sa.Column('threatlens_score', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('incidents', sa.Column('resolution_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('incidents', sa.Column('assigned_to', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_ip_address'), 'incidents', ['ip_address'], unique=False)
    # ### end Alembic commands ###
