"""add intelligence lookup table

Revision ID: fb4bd5d82dfd
Revises: 49169458b811
Create Date: 2026-08-05 17:25:17.786711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb4bd5d82dfd'
down_revision: Union[str, Sequence[str], None] = '49169458b811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intelligence_lookups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intelligence_lookups_id'), 'intelligence_lookups', ['id'], unique=False)
    op.create_index(op.f('ix_intelligence_lookups_ip'), 'intelligence_lookups', ['ip'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intelligence_lookups_ip'), table_name='intelligence_lookups')
    op.drop_index(op.f('ix_intelligence_lookups_id'), table_name='intelligence_lookups')
    op.drop_table('intelligence_lookups')
    # ### end Alembic commands ###
