"""Add incident relationship to intelligence lookups

Revision ID: fea3ba3a397d
Revises: cf14bc68d99d
Create Date: 2026-08-09 17:48:49.635169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fea3ba3a397d'
down_revision: Union[str, Sequence[str], None] = 'cf14bc68d99d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intelligence_lookups', sa.Column('incident_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_intelligence_lookups_incident_id'), 'intelligence_lookups', ['incident_id'], unique=False)
    op.create_foreign_key(None, 'intelligence_lookups', 'incidents', ['incident_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'intelligence_lookups', type_='foreignkey')
    op.drop_index(op.f('ix_intelligence_lookups_incident_id'), table_name='intelligence_lookups')
    op.drop_column('intelligence_lookups', 'incident_id')
    # ### end Alembic commands ###
